Падалко Богдан. Лабораторная работа №2.

In [1]:
import numpy as np
np.random.seed(1597463007)

Задание №5.

In [2]:
vec = np.full(10, 5.1)
print("Одномерный массив vec при помощи функции full:", vec)

Одномерный массив vec при помощи функции full: [5.1 5.1 5.1 5.1 5.1 5.1 5.1 5.1 5.1 5.1]


Задание №6

In [3]:
matr = np.random.randint(10, size = (5, 10))
print("Двумерный массив matr при помощи функции randint:")
print(matr)

Двумерный массив matr при помощи функции randint:
[[6 9 0 2 9 7 2 0 2 9]
 [3 2 8 9 5 9 5 9 4 2]
 [3 0 9 7 3 7 5 8 2 0]
 [5 5 0 7 9 4 0 2 9 0]
 [9 5 2 9 1 8 7 2 5 6]]


Задание №9

In [4]:
print("Информация о двумерном массиве matr:")
print("Тип (dtype):", matr.dtype)
print("Размерность (ndim):", matr.ndim)
print("Размерность (shape):", matr.shape)
print("Количество элементов (size):", matr.size)
print("Объём одного элемента в байтах (itemsize):", matr.itemsize)
print("Объём всего массива в байтах (nbytes):", matr.nbytes)

Информация о двумерном массиве matr:
Тип (dtype): int32
Размерность (ndim): 2
Размерность (shape): (5, 10)
Количество элементов (size): 50
Объём одного элемента в байтах (itemsize): 4
Объём всего массива в байтах (nbytes): 200


Задание №10

In [5]:
matr[2:, 4:8] += 5
print("Изменённый двумерный массив matr:")
print(matr)

Изменённый двумерный массив matr:
[[ 6  9  0  2  9  7  2  0  2  9]
 [ 3  2  8  9  5  9  5  9  4  2]
 [ 3  0  9  7  8 12 10 13  2  0]
 [ 5  5  0  7 14  9  5  7  9  0]
 [ 9  5  2  9  6 13 12  7  5  6]]


Задание №11

In [6]:
print("Скалярное произведение массивов matr и vec:")
print(np.dot(matr, vec))
print("Сумма массива matr и числа 10:")
print(np.add(matr, 10))
print("Произведение массива vec и числа 0.5:")
print(np.multiply(vec, 0.5))

Скалярное произведение массивов matr и vec:
[234.6 285.6 326.4 311.1 377.4]
Сумма массива matr и числа 10:
[[16 19 10 12 19 17 12 10 12 19]
 [13 12 18 19 15 19 15 19 14 12]
 [13 10 19 17 18 22 20 23 12 10]
 [15 15 10 17 24 19 15 17 19 10]
 [19 15 12 19 16 23 22 17 15 16]]
Произведение массива vec и числа 0.5:
[2.55 2.55 2.55 2.55 2.55 2.55 2.55 2.55 2.55 2.55]


Задание №15

In [7]:
print("L2-норма вектора vec:")
print(np.linalg.norm(vec, 2))

L2-норма вектора vec:
16.127616066858735


Задание №19

In [8]:
A = np.random.randint(10, size = (5, 5))
B = np.random.randint(10, size = (5, 5))
print("Матрица A:")
print(A)
print("Матрица B:")
print(B)
print("Сумма матриц:")
print(np.add(A, B))
print("Разность матриц:")
print(np.subtract(A, B))
print("Поэлементное произведение матриц:")
print(np.multiply(A, B))
print("Скалярное произведение матриц:")
print(np.dot(A, B))

Матрица A:
[[7 1 2 8 2]
 [7 5 6 0 4]
 [0 6 9 0 7]
 [4 3 9 3 5]
 [2 9 9 6 8]]
Матрица B:
[[3 7 9 4 3]
 [3 5 4 2 0]
 [8 2 7 0 2]
 [9 2 8 8 1]
 [3 7 1 6 1]]
Сумма матриц:
[[10  8 11 12  5]
 [10 10 10  2  4]
 [ 8  8 16  0  9]
 [13  5 17 11  6]
 [ 5 16 10 12  9]]
Разность матриц:
[[ 4 -6 -7  4 -1]
 [ 4  0  2 -2  4]
 [-8  4  2  0  5]
 [-5  1  1 -5  4]
 [-1  2  8  0  7]]
Поэлементное произведение матриц:
[[21  7 18 32  6]
 [21 25 24  0  0]
 [ 0 12 63  0 14]
 [36  6 72 24  5]
 [ 6 63  9 36  8]]
Скалярное произведение матриц:
[[118  88 147 106  35]
 [ 96 114 129  62  37]
 [111  97  94  54  25]
 [135 102 140  76  38]
 [183 145 173 122  38]]


Задание №21

In [9]:
print("Собственные значения матрицы A:")
print(np.linalg.eigvals(A))

Собственные значения матрицы A:
[24.69537494+0.j          5.17515997+3.29317708j  5.17515997-3.29317708j
 -1.52284744+1.08954185j -1.52284744-1.08954185j]


Задание №26

In [10]:
agr_arr = np.random.randint(low = -5, high = 10, size = (10, 15))
print("Сгенерированный массив:")
print(agr_arr)
print("Сумма значений элементов:")
print(np.sum(agr_arr))
print("Среднее значение элементов:")
print(np.mean(agr_arr))
print("Минимальное значение элементов:")
print(np.min(agr_arr))

Сгенерированный массив:
[[ 4  4 -2 -3  5  7  5 -2  8  2  5  6  2  5  7]
 [-5  2  1 -1  6 -4  6 -1 -5  9 -3  7 -1  4 -2]
 [ 0 -4 -2  1  0  2  6 -1  9 -2  9  3  9  0  2]
 [ 8  5  7  6  2  0 -1  9 -5  9  7  3 -1  6  4]
 [-5  7  8  4  7 -3 -5  3  5  8  1  8  9  8  8]
 [-1  1  8  8  7  2  2  2  1  3 -1  8 -3 -4  6]
 [-2  0  4  4 -3  9  2  6  0  2 -2 -4  9  0  8]
 [ 6  2 -3 -2  5  5  9 -5  0 -1  6  9 -5  5  1]
 [-3 -1  9  5 -3 -2 -5 -4 -5  6  2 -5  7  1 -2]
 [-2 -4 -1  2 -4  2 -1  3  0 -3  3  5  8  6 -1]]
Сумма значений элементов:
337
Среднее значение элементов:
2.2466666666666666
Минимальное значение элементов:
-5


Задание №32

In [11]:
agr_arr_nxt = np.random.randint(low = -5, high = 10, size = (10, 15))
print("Сгенерированный массив:")
print(agr_arr_nxt)
agr_arr_nxt[agr_arr_nxt < 0] = 0
print("Массив с заменой отрицательных элементов на 0:")
print(agr_arr_nxt)

Сгенерированный массив:
[[ 0 -3 -4 -4 -4  9  6  9  4  9 -1  4  5 -2  8]
 [-5 -1  4  8 -4 -1  5 -3 -3  1  5 -3 -1  5 -3]
 [-2  9 -1 -5 -4  2  6  5 -2  9 -1  1  9 -5 -2]
 [-2  9  9 -3 -3  1 -5  2  1  6 -4  5 -4  4  4]
 [ 2  9  0  5  6  3  1  9  2  5  5  6  0 -3  7]
 [ 0  0 -4 -5  4  7 -2  7  4  0  9  8  6  7  2]
 [ 7  0  9 -5  3  3  3  9  4  3  2  7 -2 -3  2]
 [ 0 -3 -4 -4  0  8  8 -4 -2  2  7  4  2  8 -3]
 [-5  2  9  8  3  9 -5 -2  7 -2 -3  4 -1  3  5]
 [-2  2  6  8  4 -2 -1  9  7 -5  2  7  3  5 -3]]
Массив с заменой отрицательных элементов на 0:
[[0 0 0 0 0 9 6 9 4 9 0 4 5 0 8]
 [0 0 4 8 0 0 5 0 0 1 5 0 0 5 0]
 [0 9 0 0 0 2 6 5 0 9 0 1 9 0 0]
 [0 9 9 0 0 1 0 2 1 6 0 5 0 4 4]
 [2 9 0 5 6 3 1 9 2 5 5 6 0 0 7]
 [0 0 0 0 4 7 0 7 4 0 9 8 6 7 2]
 [7 0 9 0 3 3 3 9 4 3 2 7 0 0 2]
 [0 0 0 0 0 8 8 0 0 2 7 4 2 8 0]
 [0 2 9 8 3 9 0 0 7 0 0 4 0 3 5]
 [0 2 6 8 4 0 0 9 7 0 2 7 3 5 0]]


Задание №35

Средства Numpy

In [12]:
def Numpy_AddMaxColumnToTheEnd(matr):
    return np.append(matr, np.max(matr, axis = 1).reshape(-1, 1), axis = 1)

In [13]:
%%time
print("Матрица (100*100):")
t_nm = np.random.randint(low = -5, high = 10, size = (100, 100))
t_nm = Numpy_AddMaxColumnToTheEnd(t_nm)

Матрица (100*100):
CPU times: total: 0 ns
Wall time: 1 ms


In [14]:
%%time
print("Матрица (1000*1000):")
t_nm = np.random.randint(low = -5, high = 10, size = (1000, 1000))
t_nm = Numpy_AddMaxColumnToTheEnd(t_nm)

Матрица (1000*1000):
CPU times: total: 0 ns
Wall time: 7.51 ms


In [15]:
%%time
print("Матрица (10000*10000):")
t_nm = np.random.randint(low = -5, high = 10, size = (10000, 10000))
t_nm = Numpy_AddMaxColumnToTheEnd(t_nm)

Матрица (10000*10000):
CPU times: total: 141 ms
Wall time: 601 ms


Стандартные средства Python

In [16]:
def Std_AddMaxColumnToTheEnd(matr):
    matr = np.append(matr, matr[matr.shape[0]-1].reshape(-1, 1), axis = 1)
    for i in range(0, matr.shape[0]):
        s = matr[i, 0]
        for j in range(1, matr.shape[1]-1):
            if matr[i, j] > s:
                s = matr[i, j]
        matr[i, matr.shape[1]-1] = s
    return matr

In [17]:
%%time
print("Матрица (100*100):")
t_nm = np.random.randint(low = -5, high = 10, size = (100, 100))
t_nm = Std_AddMaxColumnToTheEnd(t_nm)

Матрица (100*100):
CPU times: total: 15.6 ms
Wall time: 30.1 ms


In [18]:
%%time
print("Матрица (1000*1000):")
t_nm = np.random.randint(low = -5, high = 10, size = (1000, 1000))
t_nm = Std_AddMaxColumnToTheEnd(t_nm)

Матрица (1000*1000):
CPU times: total: 31.2 ms
Wall time: 123 ms


In [19]:
%%time
print("Матрица (10000*10000):")
t_nm = np.random.randint(low = -5, high = 10, size = (10000, 10000))
t_nm = Std_AddMaxColumnToTheEnd(t_nm)

Матрица (10000*10000):
CPU times: total: 6.11 s
Wall time: 12.2 s


Время исполнения функции при использовании средств стандартной библиотеки Python больше, чем при использовании библиотеки Numpy.

Задание №38.

In [20]:
arr = np.random.randint(low = -5, high = 10, size = (10, 20))
print("Сгенерирован массив:")
print(arr)
print("Сортированный массив:")
print(np.sort(arr, axis = None))

Сгенерирован массив:
[[ 1 -4  5 -3 -4  4  2 -2  5  2 -5  4  2  6 -4  9  4  5  7 -4]
 [ 5  1  3 -2  2 -2  3  1 -3  4  1  1  4 -3  0 -5  6  7 -1  4]
 [-4  6  2  8 -2  7  4  1 -2  2  8  3 -1  8  8  8  3  4  9 -1]
 [ 0 -4  4  1  0 -4  2 -5  5  4  9  3  0 -2  5  3  7  2  8 -5]
 [ 4 -3  4  8 -5 -1  3  4  8 -3  2  7  5  5 -2 -1  4 -3 -4  6]
 [-1  6  1  4  2 -3 -1 -3 -5  7 -2  3 -3 -2  6  2  1  2  5 -2]
 [ 8 -4  6 -1 -5  0  4  1 -3  6  4 -1 -3 -1  9  3  3 -1  3  9]
 [-2  5 -5 -5  9 -2 -4  1  2  2  0 -3 -2  7 -3 -1  4 -3 -1  4]
 [-1  5  2  4  0 -3  9  7  9  0  5 -4  1  4  0 -3  7  0  9  6]
 [ 9 -3  8  6  6  5  8  0  6  6  1  1  6 -2 -1  3 -3  0 -2  4]]
Сортированный массив:
[-5 -5 -5 -5 -5 -5 -5 -5 -5 -4 -4 -4 -4 -4 -4 -4 -4 -4 -4 -4 -3 -3 -3 -3
 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2
 -2 -2 -2 -2 -2 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  0  0  0
  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2
  2  2  2  2  2  2  2  2  2  2  2 

Задание №41

In [21]:
arr = np.random.randint(low = -5, high = 10, size = (10, 20))
print("Сгенерирован массив:")
print(arr)
np.save("LR2_41_Array", arr)
print("Массив сохранён в файл LR2_41_Array.npy.")
new_arr = np.load("LR2_41_Array.npy")
print("Массив, загруженный из файла LR2_41_Array.npy:")
print(new_arr)

Сгенерирован массив:
[[ 0 -2  8  9  2 -2 -1  1  1  5  8 -5  5 -3  8 -1  0  3  0 -3]
 [-5  6  0  2  3 -1  2  2 -3  5  8 -1  6 -5 -5 -4  9 -2  2  9]
 [-3  0  9  0  2 -3  5  8  6  7 -2 -1  4  6  9  0  0  3 -1 -3]
 [-4 -4  1  0 -4 -4  6 -1  2  7  4  0  6  8  5  2 -1 -5  8  9]
 [-1  2  1  4  5  3  5  1  7  7 -3  8  6 -2 -3  5  6  1  0  0]
 [-2  8  1 -2  8  5  7  5 -4  6  3  0  2  8  5  5 -5 -4 -1  2]
 [ 3 -4  9  2  2  6  3  5 -5  9  7  2 -5  0 -5 -1  5 -4  8 -4]
 [ 3  5 -1 -5  3  9  9 -5  5  1 -1 -2  3  1  9  3  9 -1  4  8]
 [ 1 -1  7 -2  3  7  1 -5 -4  1 -2  3  2 -5 -3  6  9 -5  3  3]
 [ 9 -2 -2  9 -2  0  8 -4  2  5  8  1 -3  7 -2  6  3  9  5 -5]]
Массив сохранён в файл LR2_41_Array.npy.
Массив, загруженный из файла LR2_41_Array.npy:
[[ 0 -2  8  9  2 -2 -1  1  1  5  8 -5  5 -3  8 -1  0  3  0 -3]
 [-5  6  0  2  3 -1  2  2 -3  5  8 -1  6 -5 -5 -4  9 -2  2  9]
 [-3  0  9  0  2 -3  5  8  6  7 -2 -1  4  6  9  0  0  3 -1 -3]
 [-4 -4  1  0 -4 -4  6 -1  2  7  4  0  6  8  5  2 -1 -5  8  9]
 [-1  2 